### ISSUE TITLE
Not detecting locale change

### ISSUE THREAD

**Issue by RomkaLTU** [GENL/matice#16]
Not sure what's a point to cache matice_translations.js in production. This file should be regenerated at least when switching locale, because now when we first visit the site, it generates:

```
locale: 'en',
fallbackLocale: 'en',
```

And that is, you stuck in EN version even if you change the locale. 

And it's ignoring:

```
'use_generated_translations_file_in_prod' => false,
```

**Comment by GENL** [comment]
The current behavior in production is for matice to generate all available translations and save them in the matice_translations.js file.

The change of locale is performed only on the js side. It does not change the locale of your backend Laravel application.

**Comment by RomkaLTU** [comment]
Ok then maybe I didn't understand the purpose of this package :/

**Comment by GENL** [comment]
Matice brings your Laravel translations to the javascript client with helpers that clone Laravel behavior. So you no longer need things like i18n or to manage two translation systems, one Laravel side and another JS side.

Updating the translations server side can be difficult, as each application has its own behavior and rules when it comes to updating the locale on the server side. Some use sessions, others persist in the database ... This is why matice lets the developer manage the locale update on the server side,

**Comment by RomkaLTU** [comment]
Initially I though that this is specifically for InertiaJS.

**Comment by GENL** [comment]
Matice is not limited to inertia or any client framework. It can even be used for SPA or classic website

**Comment by DanieleSuppo** [comment]
I'm having the same problem described by RomkaLTU and I don't know how to solve it:
when in production the backend does change the locale (because the user selected another language) the matice_translations.js is not regerated, thus does contains the old locale (and all the translations are showed in the old language).

I try to explain with an example:
- website starts in Italian
- the matice_translations.js is generated with  locale: 'it',   fallbackLocale: 'en',
- user change language to German, backend locale change to 'de'
- the matice_translations.js still has locale: 'it' 

This is the result:

![immagine](https://user-images.githubusercontent.com/2264815/131758137-b812f18c-93fc-47a5-a3b9-fea614992062.png)


I didn't find a way to separate the cache file per locale or I didn't get how I can force the regeneration of the file only when the language change.
I don't want to generate the file for each request in production, so I need the cached file but I need to tell js that the locale has changed.

**Comment by mgralikowski** [comment]
@GENL any feedback? I have the same observation. What is the purpose of caching translations? When Your library is used on production and `use_generated_translations_file_in_prod` is set as a true, a user will stuck with one language...

For now, I just disabled this option, but I would use a cached JS file to better perform. I see two solutions:
- remove `locale` from the cache
- create separate files for each language, using suffix/prefix
